name: slugify_string
version: 1.0.0
description: Converts a string into a slug. Useful for URLs, filenames, IDs, and more.
homepage: https://github.com/madewithfelt/slugify-string
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.6.2
